# Generated by Django 3.1.6 on 2021-03-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210301_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='question2',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
