# Generated by Django 3.1.6 on 2021-02-06 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210206_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ManyToManyField(default=1, to=settings.AUTH_USER_MODEL),
        ),
    ]
