# Generated by Django 3.1.6 on 2021-03-14 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210315_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='network',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
