# Generated by Django 3.1.6 on 2021-03-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question2_instruction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='answertype',
        ),
        migrations.RemoveField(
            model_name='question',
            name='default',
        ),
        migrations.RemoveField(
            model_name='question',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='question',
            name='suffix',
        ),
        migrations.AddField(
            model_name='question',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='isMandatory',
            field=models.BooleanField(default=True),
        ),
    ]
