# Generated by Django 3.1.6 on 2021-02-07 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210207_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ManyToManyField(default=1, related_name='organisation_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='core.post')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('participant', 'organisation')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='participants',
            field=models.ManyToManyField(through='core.UserOrganisation', to=settings.AUTH_USER_MODEL),
        ),
    ]
