# Generated by Django 3.1.6 on 2021-02-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210207_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creator',
        ),
    ]
