# Generated by Django 3.1.6 on 2021-03-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210319_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='methods',
            field=models.ManyToManyField(blank=True, related_name='organisations', to='core.Method'),
        ),
    ]
