# Generated by Django 3.1.6 on 2021-03-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
    ]
