# Generated by Django 3.1.6 on 2021-03-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organisation_methods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='methods',
        ),
        migrations.AddField(
            model_name='method',
            name='organisations',
            field=models.ManyToManyField(blank=True, related_name='methods', to='core.Organisation'),
        ),
    ]
