# Generated by Django 3.1.6 on 2021-02-07 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210207_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='organisation_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
