# Generated by Django 3.1.6 on 2021-03-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='ooo', to='core.QuestionOption'),
        ),
    ]
