# Generated by Django 3.1.6 on 2021-03-24 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210321_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='registered_on',
        ),
        migrations.AlterField(
            model_name='directindicator',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_indicators', to='core.question'),
        ),
    ]
