# Generated by Django 3.1.6 on 2021-03-29 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210325_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresponse',
            name='value',
        ),
        migrations.CreateModel(
            name='AnswerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=1000)),
                ('question_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.questionresponse')),
            ],
        ),
    ]
