# Generated by Django 3.1.6 on 2021-02-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210207_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='ispublic',
            field=models.BooleanField(default=True),
        ),
    ]
