# Generated by Django 3.1.6 on 2021-03-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210329_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerlist',
            name='question_response',
        ),
        migrations.RemoveField(
            model_name='answerlist',
            name='value',
        ),
        migrations.AddField(
            model_name='questionoption',
            name='question_responses',
            field=models.ManyToManyField(blank=True, related_name='values', to='core.QuestionResponse'),
        ),
    ]
