# Generated by Django 3.1.6 on 2021-03-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210329_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(related_name='surveys', to='core.DirectIndicator'),
        ),
    ]
