# Generated by Django 3.1.6 on 2021-03-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
