# Generated by Django 3.1.6 on 2021-02-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210208_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='creator',
            new_name='created_by',
        ),
    ]
