# Generated by Django 3.1.6 on 2021-03-05 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210305_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='questions_of_topic', to='core.topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='directindicator',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_indicators', to='core.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='questions',
            field=models.ManyToManyField(related_name='topics_of_questions', through='core.DirectIndicator', to='core.Question'),
        ),
    ]
