# Generated by Django 3.1.6 on 2021-02-08 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210208_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='network_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='organisation_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
