# Generated by Django 3.1.6 on 2021-03-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210305_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.CharField(blank=True, default='', max_length=45),
            preserve_default=False,
        ),
    ]
