# Generated by Django 3.1.6 on 2021-02-08 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210208_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='participants',
            field=models.ManyToManyField(related_name='participants', through='core.UserOrganisation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userorganisation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organisation'),
        ),
        migrations.AlterField(
            model_name='userorganisation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
