# Generated by Django 3.1.6 on 2021-02-08 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210208_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='participants',
            field=models.ManyToManyField(related_name='accessible_organisations', through='core.UserOrganisation', to=settings.AUTH_USER_MODEL),
        ),
    ]
