# Generated by Django 3.1.6 on 2021-03-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210309_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='networks',
        ),
    ]
