# Generated by Django 3.1.6 on 2021-02-10 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210210_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='StakeholderGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.method')),
            ],
            options={
                'verbose_name': 'stakeholder_group',
                'verbose_name_plural': 'stakeholder_groups',
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AddField(
            model_name='question',
            name='default',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='suffix',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('TEXT', 'text'), ('NUMBER', 'number'), ('RADIO', 'radio'), ('CHECKBOX', 'checkbox')], default='TEXT', max_length=100),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=45)),
                ('rate', models.IntegerField(default=0)),
                ('anonymous', models.BooleanField()),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='core.method')),
                ('questions', models.ManyToManyField(blank=True, to='core.DirectIndicator')),
                ('stakeholder_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='core.stakeholdergroup')),
            ],
            options={
                'verbose_name': 'survey',
                'verbose_name_plural': 'surveys',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('value', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.question')),
            ],
            options={
                'db_table': 'f{AppConfig.name}_question_option',
            },
        ),
    ]
