# Generated by Django 3.1.6 on 2021-02-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210211_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='content',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='title',
        ),
        migrations.AlterField(
            model_name='network',
            name='organisations',
            field=models.ManyToManyField(blank=True, to='core.Organisation'),
        ),
    ]
