# Generated by Django 3.1.6 on 2021-02-19 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210220_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='accessible_organisations', through='core.UserOrganisation', to=settings.AUTH_USER_MODEL),
        ),
    ]
