# Generated by Django 3.1.6 on 2021-02-20 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210220_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
