# Generated by Django 3.1.6 on 2021-02-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_customuser_organisations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='organisations',
        ),
    ]
